version: '3'
services:
  app:
    build: .
    image: user_docker_image
    ports:
      - "8072:8072"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresdb:5432/users
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - postgresdb
      - rabbitmq

  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=users
    volumes:
      - postgres-data:/var/lib/postgresql/events
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=maith
      - RABBITMQ_DEFAULT_PASS=4335